const vocabList = [
    { id: 1, word: "Pollution", type: "n.", meaning: "Sự ô nhiễm" },
    { id: 2, word: "Protect", type: "v.", meaning: "Bảo vệ" },
    { id: 3, word: "Garbage", type: "n.", meaning: "Rác thải" },
    { id: 4, word: "Rubbish", type: "n.", meaning: "Rác thải" },
    { id: 5, word: "Litter", type: "n.", meaning: "Rác thải" },
    { id: 6, word: "Reduce", type: "v.", meaning: "Giảm thiểu, cắt giảm" },
    { id: 7, word: "Eco-friendly", type: "adj.", meaning: "Thân thiện với môi trường" },
    { id: 8, word: "Renewable", type: "adj.", meaning: "Có thể tái tạo" },
    { id: 9, word: "Deforestation", type: "n.", meaning: "Sự tàn phá rừng" },
    { id: 10, word: "Fossil fuels", type: "n. phr.", meaning: "Nhiên liệu hóa thạch" },
    { id: 11, word: "Solar energy", type: "n. phr.", meaning: "Năng lượng mặt trời" },
    { id: 12, word: "Natural resources", type: "n. phr.", meaning: "Tài nguyên thiên nhiên" },
    { id: 13, word: "Climate change", type: "n. phr.", meaning: "Sự biến đổi khí hậu" },
    { id: 14, word: "Extinct", type: "adj.", meaning: "Tuyệt chủng" },
    { id: 15, word: "Earthquake", type: "n.", meaning: "Động đất" },
    { id: 16, word: "Flood", type: "n.", meaning: "Lũ lụt" },
    { id: 17, word: "Carbon footprint", type: "n. phr.", meaning: "Dấu chân carbon (lượng khí thải)" },
    { id: 18, word: "Plastic waste", type: "n. phr.", meaning: "Rác thải nhựa" },
    { id: 19, word: "Recycle", type: "v.", meaning: "Tái chế" },
    { id: 20, word: "Toxic chemicals", type: "n. phr.", meaning: "Hóa chất độc hại" },
    { id: 21, word: "Atmosphere", type: "n.", meaning: "Bầu khí quyển" },
    { id: 22, word: "Conservationist", type: "n.", meaning: "Nhà bảo tồn thiên nhiên" },
    { id: 23, word: "Healthy", type: "adj.", meaning: "Khỏe mạnh, lành mạnh" },
    { id: 24, word: "Diet", type: "n.", meaning: "Chế độ ăn uống" },
    { id: 25, word: "Disease", type: "n.", meaning: "Bệnh tật" },
    { id: 26, word: "Illness", type: "n.", meaning: "Bệnh tật, ốm đau" },
    { id: 27, word: "Stress", type: "n.", meaning: "Sự căng thẳng" },
    { id: 28, word: "Lifestyle", type: "n.", meaning: "Lối sống" },
    { id: 29, word: "Nutritious", type: "adj.", meaning: "Bổ dưỡng, nhiều dinh dưỡng" },
    { id: 30, word: "Mental health", type: "n. phr.", meaning: "Sức khỏe tinh thần" },
    { id: 31, word: "Physical", type: "adj.", meaning: "Thuộc về thể chất" },
    { id: 32, word: "Medicine", type: "n.", meaning: "Thuốc, y học" },
    { id: 33, word: "Pressure", type: "n.", meaning: "Áp lực" },
    { id: 34, word: "Workout", type: "n.", meaning: "Bài tập thể dục" },
    { id: 35, word: "Exercise", type: "n., v.", meaning: "Tập thể dục" },
    { id: 36, word: "Caffeine", type: "n.", meaning: "Chất cafein" },
    { id: 37, word: "Immune system", type: "n. phr.", meaning: "Hệ miễn dịch" },
    { id: 38, word: "Cancer", type: "n.", meaning: "Bệnh ung thư" },
    { id: 39, word: "Memory", type: "n.", meaning: "Trí nhớ" },
    { id: 40, word: "Energetic", type: "adj.", meaning: "Năng động, tràn đầy năng lượng" },
    { id: 41, word: "Sickness", type: "n.", meaning: "Sự ốm đau" },
    { id: 42, word: "Weight", type: "n.", meaning: "Cân nặng" },
    { id: 43, word: "Symptom", type: "n.", meaning: "Triệu chứng bệnh" },
    { id: 44, word: "Concentration", type: "n.", meaning: "Sự tập trung" },
    { id: 45, word: "Destination", type: "n.", meaning: "Điểm đến" },
    { id: 46, word: "Tourist", type: "n.", meaning: "Khách du lịch" },
    { id: 47, word: "Heritage", type: "n.", meaning: "Di sản" },
    { id: 48, word: "Accommodation", type: "n.", meaning: "Chỗ ở (khách sạn, nhà nghỉ)" },
    { id: 49, word: "Flight", type: "n.", meaning: "Chuyến bay" },
    { id: 50, word: "Landscape", type: "n.", meaning: "Phong cảnh" },
    { id: 51, word: "Scenery", type: "n.", meaning: "Phong cảnh" },
    { id: 52, word: "Attraction", type: "n.", meaning: "Điểm thu hút du lịch" },
    { id: 53, word: "Sightseeing", type: "n.", meaning: "Việc đi ngắm cảnh" },
    { id: 54, word: "Passenger", type: "n.", meaning: "Hành khách" },
    { id: 55, word: "Luggage", type: "n.", meaning: "Hành lý" },
    { id: 56, word: "Baggage", type: "n.", meaning: "Hành lý" },
    { id: 57, word: "Itinerary", type: "n.", meaning: "Lịch trình chuyến đi" },
    { id: 58, word: "Passport", type: "n.", meaning: "Hộ chiếu" },
    { id: 59, word: "Visa", type: "n.", meaning: "Thị thực" },
    { id: 60, word: "Custom", type: "n.", meaning: "Phong tục, tập quán" },
    { id: 61, word: "Book", type: "v.", meaning: "Đặt chỗ trước (vé, phòng)" },
    { id: 62, word: "Delay", type: "v., n.", meaning: "Trì hoãn, chậm trễ" },
    { id: 63, word: "Explore", type: "v.", meaning: "Khám phá" },
    { id: 64, word: "Monument", type: "n.", meaning: "Đài kỷ niệm, đài tưởng niệm" },
    { id: 65, word: "Traditional", type: "adj.", meaning: "Mang tính truyền thống" },
    { id: 66, word: "Departure", type: "n.", meaning: "Sự khởi hành" },
    { id: 67, word: "Internet", type: "n.", meaning: "Mạng internet" },
    { id: 68, word: "Network", type: "n.", meaning: "Mạng lưới" },
    { id: 69, word: "Data", type: "n.", meaning: "Dữ liệu" },
    { id: 70, word: "Device", type: "n.", meaning: "Thiết bị" },
    { id: 71, word: "Application", type: "n.", meaning: "Ứng dụng" },
    { id: 72, word: "App", type: "n.", meaning: "Ứng dụng" },
    { id: 73, word: "Smartphone", type: "n.", meaning: "Điện thoại thông minh" },
    { id: 74, word: "Connect", type: "v.", meaning: "Kết nối" },
    { id: 75, word: "Software", type: "n.", meaning: "Phần mềm" },
    { id: 76, word: "Download", type: "v.", meaning: "Tải xuống" },
    { id: 77, word: "Video", type: "n.", meaning: "Video, đoạn phim" },
    { id: 78, word: "Online", type: "adj., adv.", meaning: "Trực tuyến" },
    { id: 79, word: "Cybercrime", type: "n.", meaning: "Tội phạm mạng" },
    { id: 80, word: "Website", type: "n.", meaning: "Trang web" },
    { id: 81, word: "Message", type: "n.", meaning: "Tin nhắn, thông điệp" },
    { id: 82, word: "Digital", type: "adj.", meaning: "Kỹ thuật số" },
    { id: 83, word: "Virtual reality", type: "n. phr.", meaning: "Thực tế ảo" },
    { id: 84, word: "Electronic", type: "adj.", meaning: "Thuộc về điện tử" },
    { id: 85, word: "Technology", type: "n.", meaning: "Công nghệ" },
    { id: 86, word: "Gadget", type: "n.", meaning: "Thiết bị công nghệ tiện ích" },
    { id: 87, word: "Interact", type: "v.", meaning: "Tương tác" },
    { id: 88, word: "Knowledge", type: "n.", meaning: "Kiến thức" },
    { id: 89, word: "Experience", type: "n.", meaning: "Kinh nghiệm" },
    { id: 90, word: "Skill", type: "n.", meaning: "Kỹ năng" },
    { id: 91, word: "Graduate", type: "v.", meaning: "Tốt nghiệp" },
    { id: 92, word: "Interview", type: "n.", meaning: "Cuộc phỏng vấn" },
    { id: 93, word: "Career", type: "n.", meaning: "Sự nghiệp" },
    { id: 94, word: "Professional", type: "adj.", meaning: "Chuyên nghiệp, thuộc nghề nghiệp" },
    { id: 95, word: "Academic", type: "adj.", meaning: "Thuộc về học thuật, trường lớp" },
    { id: 96, word: "Colleague", type: "n.", meaning: "Đồng nghiệp" },
    { id: 97, word: "Qualification", type: "n.", meaning: "Bằng cấp, trình độ chuyên môn" },
    { id: 98, word: "Scientist", type: "n.", meaning: "Nhà khoa học" },
    { id: 99, word: "Mechanic", type: "n.", meaning: "Thợ máy, thợ cơ khí" },
    { id: 100, word: "Assistant", type: "n.", meaning: "Trợ lý, nhân viên bán hàng" },
    { id: 101, word: "Manager", type: "n.", meaning: "Người quản lý" },
    { id: 102, word: "Opportunity", type: "n.", meaning: "Cơ hội" },
    { id: 103, word: "Presentation", type: "n.", meaning: "Bài thuyết trình" },
    { id: 104, word: "Assignment", type: "n.", meaning: "Bài tập được giao" },
    { id: 105, word: "Training", type: "n.", meaning: "Sự đào tạo, huấn luyện" },
    { id: 106, word: "Succeed", type: "v.", meaning: "Thành công" },
    { id: 107, word: "Look after", type: "phr. v.", meaning: "Chăm sóc" },
    { id: 108, word: "Look for", type: "phr. v.", meaning: "Tìm kiếm" },
    { id: 109, word: "Look up", type: "phr. v.", meaning: "Tra cứu (từ vựng, thông tin)" },
    { id: 110, word: "Turn off", type: "phr. v.", meaning: "Tắt (thiết bị)" },
    { id: 111, word: "Turn on", type: "phr. v.", meaning: "Bật (thiết bị)" },
    { id: 112, word: "Turn down", type: "phr. v.", meaning: "Từ chối, vặn nhỏ lại" },
    { id: 113, word: "Take off", type: "phr. v.", meaning: "Cất cánh, cởi (quần áo)" },
    { id: 114, word: "Cut down on", type: "phr. v.", meaning: "Cắt giảm" },
    { id: 115, word: "Give up", type: "phr. v.", meaning: "Từ bỏ" },
    { id: 116, word: "Come down with", type: "phr. v.", meaning: "Mắc bệnh" },
    { id: 117, word: "Get on with", type: "phr. v.", meaning: "Hòa thuận, tiến triển tốt" },
    { id: 118, word: "Go on", type: "phr. v.", meaning: "Tiếp tục" },
    { id: 119, word: "Hang out", type: "phr. v.", meaning: "Đi chơi, la cà" },
    { id: 120, word: "Break down", type: "phr. v.", meaning: "Hỏng hóc (máy móc), suy sụp" },
    { id: 121, word: "Pass down", type: "phr. v.", meaning: "Truyền lại (cho thế hệ sau)" },
    { id: 122, word: "Set up", type: "phr. v.", meaning: "Thành lập, thiết lập" },
    { id: 123, word: "Grow up", type: "phr. v.", meaning: "Lớn lên, trưởng thành" },
    { id: 124, word: "Enjoy (+ V-ing)", type: "struct.", meaning: "Thích thú làm gì" },
    { id: 125, word: "Mind (+ V-ing)", type: "struct.", meaning: "Cảm thấy phiền khi làm gì" },
    { id: 126, word: "Avoid (+ V-ing)", type: "struct.", meaning: "Tránh làm gì" },
    { id: 127, word: "Suggest (+ V-ing)", type: "struct.", meaning: "Gợi ý làm gì" },
    { id: 128, word: "Deny (+ V-ing)", type: "struct.", meaning: "Phủ nhận làm gì" },
    { id: 129, word: "Decide (+ to V)", type: "struct.", meaning: "Quyết định làm gì" },
    { id: 130, word: "Expect (+ to V)", type: "struct.", meaning: "Mong đợi làm gì" },
    { id: 131, word: "Promise (+ to V)", type: "struct.", meaning: "Hứa làm gì" },
    { id: 132, word: "Refuse (+ to V)", type: "struct.", meaning: "Từ chối làm gì" },
    { id: 133, word: "Allow (+ to V)", type: "struct.", meaning: "Cho phép làm gì" },
    { id: 134, word: "Pollute", type: "v.", meaning: "Làm ô nhiễm" },
    { id: 135, word: "Preserve", type: "v.", meaning: "Bảo tồn, giữ gìn" },
    { id: 136, word: "Conserve", type: "v.", meaning: "Bảo tồn (năng lượng, tài nguyên)" },
    { id: 137, word: "Destroy", type: "v.", meaning: "Phá hủy" },
    { id: 138, word: "Damage", type: "v.", meaning: "Gây thiệt hại" },
    { id: 139, word: "Invent", type: "v.", meaning: "Phát minh" },
    { id: 140, word: "Discover", type: "v.", meaning: "Khám phá, phát hiện ra" },
    { id: 141, word: "Improve", type: "v.", meaning: "Cải thiện, nâng cao" },
    { id: 142, word: "Provide", type: "v.", meaning: "Cung cấp" },
    { id: 143, word: "Encourage", type: "v.", meaning: "Khuyến khích" },
    { id: 144, word: "Support", type: "v.", meaning: "Hỗ trợ" },
    { id: 145, word: "Explain", type: "v.", meaning: "Giải thích" },
    { id: 146, word: "Discuss", type: "v.", meaning: "Thảo luận" },
    { id: 147, word: "Concentrate (on)", type: "v.", meaning: "Tập trung vào" },
    { id: 148, word: "Focus (on)", type: "v.", meaning: "Tập trung vào" },
    { id: 149, word: "Prepare", type: "v.", meaning: "Chuẩn bị" },
    { id: 150, word: "Require", type: "v.", meaning: "Yêu cầu, đòi hỏi" },
    { id: 151, word: "Achieve", type: "v.", meaning: "Đạt được (thành tựu)" },
    { id: 152, word: "Collaborate", type: "v.", meaning: "Hợp tác" },
    { id: 153, word: "Remind", type: "v.", meaning: "Nhắc nhở" },
    { id: 154, word: "Complain", type: "v.", meaning: "Phàn nàn" },
    { id: 155, word: "Attract", type: "v.", meaning: "Thu hút" },
    { id: 156, word: "Celebrate", type: "v.", meaning: "Ăn mừng, kỷ niệm" },
    { id: 157, word: "Depend (on)", type: "v.", meaning: "Phụ thuộc vào" },
    { id: 158, word: "Affect", type: "v.", meaning: "Tác động, ảnh hưởng" },
    { id: 159, word: "Cause", type: "v.", meaning: "Gây ra" },
    { id: 160, word: "Benefit", type: "v.", meaning: "Hưởng lợi, mang lại lợi ích" },
    { id: 161, word: "Solve", type: "v.", meaning: "Giải quyết (vấn đề)" },
    { id: 162, word: "Prevent", type: "v.", meaning: "Ngăn chặn" },
    { id: 163, word: "Participate (in)", type: "v.", meaning: "Tham gia vào" },
    { id: 164, word: "Organize", type: "v.", meaning: "Tổ chức" },
    { id: 165, word: "Be (am/is/are/was/were)", type: "v.", meaning: "Thì, là, ở" },
    { id: 166, word: "Have / Has / Had", type: "v.", meaning: "Có" },
    { id: 167, word: "Do / Does / Did", type: "v.", meaning: "Làm" },
    { id: 168, word: "Go", type: "v.", meaning: "Đi" },
    { id: 169, word: "Come", type: "v.", meaning: "Đến" },
    { id: 170, word: "Take (Take care of)", type: "v.", meaning: "Cầm, lấy, dẫn đi (Chăm sóc)" },
    { id: 171, word: "Make", type: "v.", meaning: "Làm, tạo ra" },
    { id: 172, word: "Get (Get up)", type: "v.", meaning: "Lấy, nhận được (Thức dậy)" },
    { id: 173, word: "See", type: "v.", meaning: "Nhìn thấy" },
    { id: 174, word: "Look (Look for)", type: "v.", meaning: "Nhìn (Tìm kiếm)" },
    { id: 175, word: "Watch", type: "v.", meaning: "Xem (TV, phim)" },
    { id: 176, word: "Listen (to)", type: "v.", meaning: "Lắng nghe" },
    { id: 177, word: "Learn", type: "v.", meaning: "Học" },
    { id: 178, word: "Study", type: "v.", meaning: "Học, nghiên cứu" },
    { id: 179, word: "Read", type: "v.", meaning: "Đọc" },
    { id: 180, word: "Write", type: "v.", meaning: "Viết" },
    { id: 181, word: "Speak", type: "v.", meaning: "Nói" },
    { id: 182, word: "Work", type: "v., n.", meaning: "Làm việc, công việc" },
    { id: 183, word: "Help", type: "v., n.", meaning: "Giúp đỡ" },
    { id: 184, word: "Use", type: "v.", meaning: "Sử dụng" },
    { id: 185, word: "Like", type: "v.", meaning: "Thích" },
    { id: 186, word: "Love", type: "v.", meaning: "Yêu, thích" },
    { id: 187, word: "Enjoy", type: "v.", meaning: "Thích thú, tận hưởng" },
    { id: 188, word: "Want", type: "v.", meaning: "Muốn" },
    { id: 189, word: "Need", type: "v.", meaning: "Cần" },
    { id: 190, word: "Wish", type: "v.", meaning: "Ước" },
    { id: 191, word: "Hope", type: "v.", meaning: "Hy vọng" },
    { id: 192, word: "Think", type: "v.", meaning: "Nghĩ" },
    { id: 193, word: "Know", type: "v.", meaning: "Biết" },
    { id: 194, word: "Ask", type: "v.", meaning: "Hỏi, yêu cầu" },
    { id: 195, word: "Tell", type: "v.", meaning: "Bảo, kể" },
    { id: 196, word: "Say", type: "v.", meaning: "Nói" },
    { id: 197, word: "Talk", type: "v.", meaning: "Nói chuyện" },
    { id: 198, word: "Call", type: "v.", meaning: "Gọi điện thoại" },
    { id: 199, word: "Buy", type: "v.", meaning: "Mua" },
    { id: 200, word: "Sell", type: "v.", meaning: "Bán" },
    { id: 201, word: "Pay", type: "v.", meaning: "Trả tiền" },
    { id: 202, word: "Spend", type: "v.", meaning: "Dành (thời gian), tiêu (tiền)" },
    { id: 203, word: "Save", type: "v.", meaning: "Tiết kiệm, cứu" },
    { id: 204, word: "Live", type: "v.", meaning: "Sống" },
    { id: 205, word: "Visit", type: "v.", meaning: "Thăm (ông bà, địa điểm)" },
    { id: 206, word: "Play", type: "v.", meaning: "Chơi" },
    { id: 207, word: "Start / Begin", type: "v.", meaning: "Bắt đầu" },
    { id: 208, word: "Finish / End", type: "v.", meaning: "Kết thúc" },
    { id: 209, word: "Stop", type: "v.", meaning: "Dừng lại" },
    { id: 210, word: "Change", type: "v., n.", meaning: "Thay đổi, sự thay đổi" },
    { id: 211, word: "Happen", type: "v.", meaning: "Xảy ra" },
    { id: 212, word: "Student / Pupil", type: "n.", meaning: "Học sinh" },
    { id: 213, word: "Teacher", type: "n.", meaning: "Giáo viên" },
    { id: 214, word: "Friend", type: "n.", meaning: "Bạn bè" },
    { id: 215, word: "Family", type: "n.", meaning: "Gia đình" },
    { id: 216, word: "Parents", type: "n.", meaning: "Bố mẹ" },
    { id: 217, word: "People", type: "n.", meaning: "Mọi người" },
    { id: 218, word: "Child / Children", type: "n.", meaning: "Trẻ em" },
    { id: 219, word: "Man / Men", type: "n.", meaning: "Đàn ông" },
    { id: 220, word: "Woman / Women", type: "n.", meaning: "Phụ nữ" },
    { id: 221, word: "Doctor", type: "n.", meaning: "Bác sĩ" },
    { id: 222, word: "School", type: "n.", meaning: "Trường học" },
    { id: 223, word: "Class", type: "n.", meaning: "Lớp học" },
    { id: 224, word: "House / Home", type: "n.", meaning: "Ngôi nhà" },
    { id: 225, word: "Room", type: "n.", meaning: "Căn phòng" },
    { id: 226, word: "City", type: "n.", meaning: "Thành phố" },
    { id: 227, word: "Country", type: "n.", meaning: "Đất nước / Vùng quê" },
    { id: 228, word: "World", type: "n.", meaning: "Thế giới" },
    { id: 229, word: "Hospital", type: "n.", meaning: "Bệnh viện" },
    { id: 230, word: "Market", type: "n.", meaning: "Chợ" },
    { id: 231, word: "Environment", type: "n.", meaning: "Môi trường" },
    { id: 232, word: "Garbage / Trash / Rubbish", type: "n.", meaning: "Rác" },
    { id: 233, word: "Water", type: "n.", meaning: "Nước" },
    { id: 234, word: "Air", type: "n.", meaning: "Không khí" },
    { id: 235, word: "Tree", type: "n.", meaning: "Cái cây" },
    { id: 236, word: "Animal", type: "n.", meaning: "Động vật" },
    { id: 237, word: "Food", type: "n.", meaning: "Thức ăn" },
    { id: 238, word: "Meal", type: "n.", meaning: "Bữa ăn" },
    { id: 239, word: "Health", type: "n.", meaning: "Sức khỏe" },
    { id: 240, word: "Problem", type: "n.", meaning: "Vấn đề" },
    { id: 241, word: "Money", type: "n.", meaning: "Tiền" },
    { id: 242, word: "Job / Work", type: "n.", meaning: "Công việc" },
    { id: 243, word: "Life", type: "n.", meaning: "Cuộc sống" },
    { id: 244, word: "Thing", type: "n.", meaning: "Thứ, đồ vật" },
    { id: 245, word: "Time", type: "n.", meaning: "Thời gian" },
    { id: 246, word: "Day", type: "n.", meaning: "Ngày" },
    { id: 247, word: "Week", type: "n.", meaning: "Tuần" },
    { id: 248, word: "Month", type: "n.", meaning: "Tháng" },
    { id: 249, word: "Year", type: "n.", meaning: "Năm" },
    { id: 250, word: "Morning / Afternoon / Evening", type: "n.", meaning: "Sáng / Chiều / Tối" },
    { id: 251, word: "Car", type: "n.", meaning: "Ô tô" },
    { id: 252, word: "Bus", type: "n.", meaning: "Xe buýt" },
    { id: 253, word: "Traffic", type: "n.", meaning: "Giao thông" },
    { id: 254, word: "Trip", type: "n.", meaning: "Chuyến đi" },
    { id: 255, word: "Holiday", type: "n.", meaning: "Kỳ nghỉ" },
    { id: 256, word: "Computer", type: "n.", meaning: "Máy tính" },
    { id: 257, word: "Phone", type: "n.", meaning: "Điện thoại" },
    { id: 258, word: "Information", type: "n.", meaning: "Thông tin" },
    { id: 259, word: "Look at", type: "phr. v.", meaning: "Nhìn vào" },
    { id: 260, word: "Look out", type: "phr. v.", meaning: "Coi chừng, cẩn thận" },
    { id: 261, word: "Look down on", type: "phr. v.", meaning: "Coi thường" },
    { id: 262, word: "Look forward to", type: "phr. v.", meaning: "Mong đợi" },
    { id: 263, word: "Turn up", type: "phr. v.", meaning: "Vặn to âm lượng / Xuất hiện" },
    { id: 264, word: "Switch off", type: "phr. v.", meaning: "Tắt (điện, đèn)" },
    { id: 265, word: "Switch to", type: "phr. v.", meaning: "Chuyển sang (phương án khác)" },
    { id: 266, word: "Take on", type: "phr. v.", meaning: "Đảm nhận (công việc, trách nhiệm)" },
    { id: 267, word: "Take up", type: "phr. v.", meaning: "Bắt đầu một sở thích/thói quen mới" },
    { id: 268, word: "Take apart", type: "phr. v.", meaning: "Tháo rời ra" },
    { id: 269, word: "Take away", type: "phr. v.", meaning: "Lấy đi, mang đi" },
    { id: 270, word: "Take part in", type: "phr. v.", meaning: "Tham gia vào" },
    { id: 271, word: "Put on", type: "phr. v.", meaning: "Mặc vào, mang vào" },
    { id: 272, word: "Put off", type: "phr. v.", meaning: "Trì hoãn" },
    { id: 273, word: "Put up", type: "phr. v.", meaning: "Dựng lên (lều), treo lên" },
    { id: 274, word: "Put out", type: "phr. v.", meaning: "Dập tắt (lửa, đám cháy)" },
    { id: 275, word: "Put down", type: "phr. v.", meaning: "Đặt xuống" },
    { id: 276, word: "Get up", type: "phr. v.", meaning: "Thức dậy" },
    { id: 277, word: "Get on", type: "phr. v.", meaning: "Lên xe (xe buýt, tàu) / Tiến triển" },
    { id: 278, word: "Get off", type: "phr. v.", meaning: "Xuống xe" },
    { id: 279, word: "Get over", type: "phr. v.", meaning: "Vượt qua (bệnh tật, khó khăn)" },
    { id: 280, word: "Get around", type: "phr. v.", meaning: "Đi lại, di chuyển trong khu vực" },
    { id: 281, word: "Get along (with)", type: "phr. v.", meaning: "Hòa thuận với ai" },
    { id: 282, word: "Go out", type: "phr. v.", meaning: "Đi ra ngoài, đi chơi" },
    { id: 283, word: "Go against", type: "phr. v.", meaning: "Đi ngược lại, chống lại (quy tắc)" },
    { id: 284, word: "Go over", type: "phr. v.", meaning: "Kiểm tra lại, xem xét kỹ" },
    { id: 285, word: "Come back", type: "phr. v.", meaning: "Quay trở lại" },
    { id: 286, word: "Come over", type: "phr. v.", meaning: "Ghé thăm nhà" },
    { id: 287, word: "Come out", type: "phr. v.", meaning: "Ra mắt, xuất bản" },
    { id: 288, word: "Come in", type: "phr. v.", meaning: "Đi vào" },
    { id: 289, word: "Come up with", type: "phr. v.", meaning: "Nảy ra ý tưởng, tìm ra giải pháp" },
    { id: 290, word: "Bring up", type: "phr. v.", meaning: "Nuôi dưỡng / Đề cập đến" },
    { id: 291, word: "Bring back", type: "phr. v.", meaning: "Gợi lại (kỉ niệm)" },
    { id: 292, word: "Bring about", type: "phr. v.", meaning: "Mang lại, gây ra (sự thay đổi)" },
    { id: 293, word: "Bring along", type: "phr. v.", meaning: "Mang theo cùng" },
    { id: 294, word: "Bring in", type: "phr. v.", meaning: "Kiếm tiền, mang lại thu nhập" },
    { id: 295, word: "Catch up with", type: "phr. v.", meaning: "Bắt kịp, theo kịp ai/cái gì" },
    { id: 296, word: "Catch on", type: "phr. v.", meaning: "Trở nên phổ biến" },
    { id: 297, word: "Keep on", type: "phr. v.", meaning: "Tiếp tục làm gì" },
    { id: 298, word: "Keep up", type: "phr. v.", meaning: "Duy trì (mối quan hệ)" },
    { id: 299, word: "Break up", type: "phr. v.", meaning: "Chia tay, chấm dứt mối quan hệ" },
    { id: 300, word: "Hang out (with)", type: "phr. v.", meaning: "Đi chơi, la cà với bạn bè" },
    { id: 301, word: "Give away", type: "phr. v.", meaning: "Cho, tặng đi" },
    { id: 302, word: "Find out", type: "phr. v.", meaning: "Tìm ra, phát hiện ra" },
    { id: 303, word: "Carry out", type: "phr. v.", meaning: "Tiến hành, thực hiện (kế hoạch)" },
    { id: 304, word: "Clean up", type: "phr. v.", meaning: "Dọn dẹp sạch sẽ" },
    { id: 305, word: "Wake up", type: "phr. v.", meaning: "Thức giấc" },
    { id: 306, word: "Stay up", type: "phr. v.", meaning: "Thức khuya" },
    { id: 307, word: "Live up to", type: "phr. v.", meaning: "Đáp ứng được kỳ vọng" },
    { id: 308, word: "Use up", type: "phr. v.", meaning: "Sử dụng hết sạch (tài nguyên)" },
    { id: 309, word: "Wash down", type: "phr. v.", meaning: "Uống nước để nuốt trôi thức ăn" },
    { id: 310, word: "Split up", type: "phr. v.", meaning: "Chia tay, rã đám (ban nhạc)" },
    { id: 311, word: "Pick up", type: "phr. v.", meaning: "Nhặt lên, đón ai đó, học lỏm" },
    { id: 312, word: "Cheer up", type: "phr. v.", meaning: "Làm ai đó vui lên" },
    { id: 313, word: "Stand up", type: "phr. v.", meaning: "Đứng lên" },
    { id: 314, word: "Call on", type: "phr. v.", meaning: "Gọi tên, yêu cầu phát biểu" },
    { id: 315, word: "Rely on", type: "phr. v.", meaning: "Dựa vào, nhờ cậy vào" },
    { id: 316, word: "Depend on", type: "phr. v.", meaning: "Phụ thuộc vào" },
    { id: 317, word: "Focus on", type: "phr. v.", meaning: "Tập trung vào" },
    { id: 318, word: "Lead to", type: "phr. v.", meaning: "Dẫn đến (hậu quả, vấn đề)" },
    { id: 319, word: "Result in", type: "phr. v.", meaning: "Dẫn đến kết quả" },
    { id: 320, word: "Belong to", type: "phr. v.", meaning: "Thuộc về ai/cái gì" },
    { id: 321, word: "Believe in", type: "phr. v.", meaning: "Tin tưởng vào" },
    { id: 322, word: "Succeed in", type: "phr. v.", meaning: "Thành công trong việc gì" },
    { id: 323, word: "Work out", type: "phr. v.", meaning: "Tập thể hình / Tìm ra giải pháp" },
    { id: 324, word: "Check out", type: "phr. v.", meaning: "Kiểm tra, xem thử" },
    { id: 325, word: "Check in", type: "phr. v.", meaning: "Làm thủ tục (sân bay, khách sạn)" },
    { id: 326, word: "Sign out", type: "phr. v.", meaning: "Đăng xuất, ký tên rời đi" },
    { id: 327, word: "Shut down", type: "phr. v.", meaning: "Đóng cửa, ngừng hoạt động" },
    { id: 328, word: "Pull over", type: "phr. v.", meaning: "Tấp xe vào lề đường" },
    { id: 329, word: "Hand in", type: "phr. v.", meaning: "Nộp bài, giao nộp" },
    { id: 330, word: "Fill in", type: "phr. v.", meaning: "Điền vào (đơn, mẫu)" },
    { id: 331, word: "Let down", type: "phr. v.", meaning: "Làm ai đó thất vọng" },
    { id: 332, word: "Calm down", type: "phr. v.", meaning: "Bình tĩnh lại" },
    { id: 333, word: "Start up", type: "phr. v.", meaning: "Khởi nghiệp, bắt đầu" },
    { id: 334, word: "Roll around", type: "phr. v.", meaning: "Lăn lộn, đùa giỡn" },
    { id: 335, word: "Show around", type: "phr. v.", meaning: "Dẫn đi tham quan vòng quanh" },
    { id: 336, word: "Settle into", type: "phr. v.", meaning: "Làm quen với, ổn định" },
    { id: 337, word: "Fall off", type: "phr. v.", meaning: "Ngã khỏi (xe đạp, lưng ngựa)" },
    { id: 338, word: "Step back", type: "phr. v.", meaning: "Lùi lại một bước" },
    { id: 339, word: "Hold down", type: "phr. v.", meaning: "Kìm hãm, đè nén" },
    { id: 340, word: "Build up", type: "phr. v.", meaning: "Xây dựng, phát triển dần dần" },
    { id: 341, word: "Wait for", type: "phr. v.", meaning: "Chờ đợi" },
    { id: 342, word: "Pay for", type: "phr. v.", meaning: "Trả tiền cho" },
    { id: 343, word: "Think about", type: "phr. v.", meaning: "Suy nghĩ về" },
    { id: 344, word: "Talk about", type: "phr. v.", meaning: "Nói chuyện về" },
    { id: 345, word: "According to", type: "prep.", meaning: "Theo như" },
    { id: 346, word: "Main idea", type: "n. phr.", meaning: "Ý chính" },
    { id: 347, word: "Best title", type: "n. phr.", meaning: "Tiêu đề đúng nhất" },
    { id: 348, word: "Mention", type: "v.", meaning: "Đề cập đến" },
    { id: 349, word: "Not mentioned", type: "phr.", meaning: "Không được đề cập" },
    { id: 350, word: "Infer", type: "v.", meaning: "Suy ra" },
    { id: 351, word: "Imply", type: "v.", meaning: "Ngụ ý" },
    { id: 352, word: "Refer to", type: "phr. v.", meaning: "Thay thế cho, ám chỉ" },
    { id: 353, word: "Closest in meaning", type: "phr.", meaning: "Gần nghĩa nhất" },
    { id: 354, word: "Opposite in meaning", type: "phr.", meaning: "Trái nghĩa nhất" },
    { id: 355, word: "Synonym", type: "n.", meaning: "Từ đồng nghĩa" },
    { id: 356, word: "Antonym", type: "n.", meaning: "Từ trái nghĩa" },
    { id: 357, word: "TRUE", type: "adj.", meaning: "Đúng" },
    { id: 358, word: "FALSE", type: "adj.", meaning: "Sai" },
    { id: 359, word: "Except", type: "prep., conj.", meaning: "Ngoại trừ" },
    { id: 360, word: "Statement", type: "n.", meaning: "Câu phát biểu" },
    { id: 361, word: "Replace", type: "v.", meaning: "Thay thế" },
    { id: 362, word: "Paragraph", type: "n.", meaning: "Đoạn văn" },
    { id: 363, word: "Blank", type: "n.", meaning: "Chỗ trống" },
    { id: 364, word: "Space", type: "n.", meaning: "Chỗ trống, khoảng không" },
    { id: 365, word: "Describe", type: "v.", meaning: "Miêu tả" },
    { id: 366, word: "Reason", type: "n.", meaning: "Lý do" },
    { id: 367, word: "Purpose", type: "n.", meaning: "Mục đích" },
    { id: 368, word: "However", type: "adv.", meaning: "Tuy nhiên" },
    { id: 369, word: "Therefore", type: "adv.", meaning: "Vì vậy, do đó" },
    { id: 370, word: "Although", type: "conj.", meaning: "Mặc dù" },
    { id: 371, word: "Even though", type: "conj.", meaning: "Mặc dù" },
    { id: 372, word: "Because of", type: "prep.", meaning: "Bởi vì" },
    { id: 373, word: "Due to", type: "prep.", meaning: "Bởi vì, do" },
    { id: 374, word: "In addition", type: "phr.", meaning: "Thêm vào đó" },
    { id: 375, word: "Moreover", type: "adv.", meaning: "Ngoài ra" },
    { id: 376, word: "Besides", type: "adv., prep.", meaning: "Bên cạnh đó" },
    { id: 377, word: "Furthermore", type: "adv.", meaning: "Hơn thế nữa" },
    { id: 378, word: "As a result", type: "phr.", meaning: "Kết quả là" },
    { id: 379, word: "Consequently", type: "adv.", meaning: "Kết quả là" },
    { id: 380, word: "Instead of", type: "prep.", meaning: "Thay vì" },
    { id: 381, word: "Especially", type: "adv.", meaning: "Đặc biệt là" },
    { id: 382, word: "Particularly", type: "adv.", meaning: "Đặc biệt là" },
    { id: 383, word: "Actually", type: "adv.", meaning: "Thực ra" },
    { id: 384, word: "In fact", type: "phr.", meaning: "Trên thực tế" },
    { id: 385, word: "Unfortunately", type: "adv.", meaning: "Thật không may" },
    { id: 386, word: "Luckily", type: "adv.", meaning: "Thật may mắn" },
    { id: 387, word: "Fortunately", type: "adv.", meaning: "Thật may mắn" },
    { id: 388, word: "Recently", type: "adv.", meaning: "Gần đây" },
    { id: 389, word: "Nowadays", type: "adv.", meaning: "Ngày nay" },
    { id: 390, word: "Immediately", type: "adv.", meaning: "Ngay lập tức" },
    { id: 391, word: "Rapidly", type: "adv.", meaning: "Nhanh chóng" },
    { id: 392, word: "Quickly", type: "adv.", meaning: "Nhanh chóng" },
    { id: 393, word: "Slowly", type: "adv.", meaning: "Chậm chạp" },
    { id: 394, word: "Gradually", type: "adv.", meaning: "Dần dần" },
    { id: 395, word: "Significantly", type: "adv.", meaning: "Một cách đáng kể" },
    { id: 396, word: "Simply", type: "adv.", meaning: "Một cách đơn giản" },
    { id: 397, word: "Regularly", type: "adv.", meaning: "Thường xuyên" },
    { id: 398, word: "Constantly", type: "adv.", meaning: "Liên tục" },
    { id: 399, word: "Important", type: "adj.", meaning: "Rất quan trọng" },
    { id: 400, word: "Crucial", type: "adj.", meaning: "Chủ yếu, cốt yếu" },
    { id: 401, word: "Vital", type: "adj.", meaning: "Thiết yếu" },
    { id: 402, word: "Necessary", type: "adj.", meaning: "Cần thiết" },
    { id: 403, word: "Essential", type: "adj.", meaning: "Cần thiết, thiết yếu" },
    { id: 404, word: "Popular", type: "adj.", meaning: "Phổ biến" },
    { id: 405, word: "Common", type: "adj.", meaning: "Thông dụng, chung" },
    { id: 406, word: "Famous", type: "adj.", meaning: "Nổi tiếng" },
    { id: 407, word: "Well-known", type: "adj.", meaning: "Nổi tiếng" },
    { id: 408, word: "Modern", type: "adj.", meaning: "Hiện đại" },
    { id: 409, word: "Convenient", type: "adj.", meaning: "Thuận tiện" },
    { id: 410, word: "Comfortable", type: "adj.", meaning: "Thoải mái" },
    { id: 411, word: "Dangerous", type: "adj.", meaning: "Nguy hiểm" },
    { id: 412, word: "Safe", type: "adj.", meaning: "An toàn" },
    { id: 413, word: "Expensive", type: "adj.", meaning: "Đắt đỏ" },
    { id: 414, word: "Costly", type: "adj.", meaning: "Tốn kém, đắt" },
    { id: 415, word: "Cheap", type: "adj.", meaning: "Rẻ" },
    { id: 416, word: "Inexpensive", type: "adj.", meaning: "Không đắt, rẻ" },
    { id: 417, word: "Difficult", type: "adj.", meaning: "Khó khăn" },
    { id: 418, word: "Hard", type: "adj.", meaning: "Khó khăn, cứng" },
    { id: 419, word: "Easy", type: "adj.", meaning: "Dễ dàng" },
    { id: 420, word: "Simple", type: "adj.", meaning: "Đơn giản" },
    { id: 421, word: "Beautiful", type: "adj.", meaning: "Đẹp" },
    { id: 422, word: "Attractive", type: "adj.", meaning: "Thu hút" },
    { id: 423, word: "Stunning", type: "adj.", meaning: "Đẹp sững sờ" },
    { id: 424, word: "Useful", type: "adj.", meaning: "Hữu ích" },
    { id: 425, word: "Helpful", type: "adj.", meaning: "Hữu ích, hay giúp đỡ" },
    { id: 426, word: "Harmful", type: "adj.", meaning: "Có hại" },
    { id: 427, word: "Detrimental", type: "adj.", meaning: "Có hại, bất lợi" },
    { id: 428, word: "Successful", type: "adj.", meaning: "Thành công" },
    { id: 429, word: "Available", type: "adj.", meaning: "Có sẵn" },
    { id: 430, word: "Natural", type: "adj.", meaning: "Thuộc về tự nhiên" },
    { id: 431, word: "Advantage", type: "n.", meaning: "Lợi ích, ưu điểm" },
    { id: 432, word: "Disadvantage", type: "n.", meaning: "Bất lợi, nhược điểm" },
    { id: 433, word: "Drawback", type: "n.", meaning: "Điểm hạn chế" },
    { id: 434, word: "Impact", type: "n.", meaning: "Sự tác động" },
    { id: 435, word: "Effect", type: "n.", meaning: "Hiệu ứng, ảnh hưởng" },
    { id: 436, word: "Influence", type: "n.", meaning: "Sự ảnh hưởng" },
    { id: 437, word: "Solution", type: "n.", meaning: "Giải pháp" },
    { id: 438, word: "Chance", type: "n.", meaning: "Cơ hội, sự tình cờ" },
    { id: 439, word: "Challenge", type: "n.", meaning: "Thử thách" },
    { id: 440, word: "Issue", type: "n.", meaning: "Vấn đề" },
    { id: 441, word: "Habit", type: "n.", meaning: "Thói quen" },
    { id: 442, word: "Routine", type: "n.", meaning: "Thói quen, sinh hoạt hàng ngày" },
    { id: 443, word: "Choice", type: "n.", meaning: "Sự lựa chọn" },
    { id: 444, word: "Option", type: "n.", meaning: "Tùy chọn, sự lựa chọn" },
    { id: 445, word: "Source", type: "n.", meaning: "Nguồn" },
    { id: 446, word: "Population", type: "n.", meaning: "Dân số" },
    { id: 447, word: "Community", type: "n.", meaning: "Cộng đồng" },
    { id: 448, word: "Culture", type: "n.", meaning: "Văn hóa" },
    { id: 449, word: "Equipment", type: "n.", meaning: "Thiết bị" },
    { id: 450, word: "Transport", type: "n.", meaning: "Giao thông" },
    { id: 451, word: "Vehicle", type: "n.", meaning: "Phương tiện" },
    { id: 452, word: "Nutrition", type: "n.", meaning: "Dinh dưỡng" },
    { id: 453, word: "Enhance", type: "v.", meaning: "Nâng cao" },
    { id: 454, word: "Develop", type: "v.", meaning: "Phát triển" },
    { id: 455, word: "Offer", type: "v.", meaning: "Đưa ra, cung cấp" },
    { id: 456, word: "Decrease", type: "v.", meaning: "Làm giảm" },
    { id: 457, word: "Increase", type: "v.", meaning: "Tăng lên" },
    { id: 458, word: "Avoid", type: "v.", meaning: "Tránh" },
    { id: 459, word: "Handle", type: "v.", meaning: "Xử lý, giải quyết" },
    { id: 460, word: "Hold", type: "v.", meaning: "Tổ chức, cầm, giữ" },
    { id: 461, word: "Participate in", type: "phr. v.", meaning: "Tham gia vào" },
    { id: 462, word: "Join", type: "v.", meaning: "Tham gia" },
    { id: 463, word: "Believe", type: "v.", meaning: "Tin rằng" },
    { id: 464, word: "Suggest", type: "v.", meaning: "Đề nghị, gợi ý" },
    { id: 465, word: "Recommend", type: "v.", meaning: "Gợi ý, tiến cử" },
    { id: 466, word: "Concentrate on", type: "phr. v.", meaning: "Tập trung vào" },
    { id: 467, word: "Loss of life", type: "n", meaning: "Thiệt hại về người" },
    { id: 468, word: "Property", type: "n", meaning: "Tài sản (nhà cửa, của cải)" },
    { id: 469, word: "Displacement", type: "n", meaning: "Sự di dời (phải rời bỏ nhà cửa)" },
    { id: 470, word: "Warning systems", type: "n", meaning: "Hệ thống cảnh báo (sớm)" },
    { id: 471, word: "Safety measure", type: "n", meaning: "Biện pháp an toàn" },
    { id: 472, word: "Emergency response plans", type: "Cụm n", meaning: "Kế hoạch ứng phó khẩn cấp" },
    { id: 473, word: "Sales assistant", type: "n", meaning: "Nhân viên bán hàng" },
    { id: 474, word: "Customer", type: "n", meaning: "Khách hàng" },
    { id: 475, word: "Cash register", type: "n", meaning: "Máy tính tiền" },
    { id: 476, word: "Salary", type: "n", meaning: "Tiền lương" },
    { id: 477, word: "Discount", type: "n", meaning: "Sự giảm giá" },
    { id: 478, word: "Apply", type: "v", meaning: "Nộp đơn (xin việc)" },
    { id: 479, word: "Expert", type: "n", meaning: "Chuyên gia" },
    { id: 480, word: "Lose", type: "v", meaning: "Đánh mất" },
    { id: 481, word: "Lack", type: "v", meaning: "Thiếu" },
    { id: 482, word: "Valuable", type: "adj", meaning: "Có giá trị" },
    { id: 483, word: "Permanently", type: "adv", meaning: "Vĩnh viễn" },
    { id: 484, word: "Hurricane", type: "n", meaning: "Bão lớn" },
    { id: 485, word: "Wildfire", type: "n", meaning: "Cháy rừng" },
    { id: 486, word: "Drought", type: "n", meaning: "Hạn hán" },
    { id: 487, word: "Destruction", type: "n, v", meaning: "Sự tàn phá, thiệt hại" },
    { id: 488, word: "Chef", type: "n", meaning: "Đầu bếp" },
    { id: 489, word: "Artist", type: "n", meaning: "Nghệ nhân" },
    { id: 490, word: "Virtual", type: "n, adj", meaning: "Ảo" },
    { id: 491, word: "Clean energy", type: "n", meaning: "năng lượng sạch" },
    // Lỗi: Không thể phân tích dòng "492	Create		Tạo ra"
    // Lỗi: Không thể phân tích dòng "493	Generate		Tạo ra"
    // Lỗi: Không thể phân tích dòng "494	Produce		Tạo ra"
    // Lỗi: Không thể phân tích dòng "495	Habitat		Môi trường sống"
    // Lỗi: Không thể phân tích dòng "496	Gain		Đạt được"
    // Lỗi: Không thể phân tích dòng "497	Get		thu được"
    // Lỗi: Không thể phân tích dòng "498	Occur		Xảy ra"
    // Lỗi: Không thể phân tích dòng "499	Take place		Xảy ra"
    // Lỗi: Không thể phân tích dòng "500	Mitigate		Giảm thiểu"
    // Lỗi: Không thể phân tích dòng "501	Decline		Giảm thiểu"
    // Lỗi: Không thể phân tích dòng "502	Severe		Nghiêm trọng"
    // Lỗi: Không thể phân tích dòng "503	Serious		Nghiêm trọng"
    // Lỗi: Không thể phân tích dòng "504	Appear		Xuất hiện"
    // Lỗi: Không thể phân tích dòng "505	Disappear		Biến mất"
    // Lỗi: Không thể phân tích dòng "506	Future		Tương lai"
    // Lỗi: Không thể phân tích dòng "507	History		Quá khứ"
    // Lỗi: Không thể phân tích dòng "508	Outside		Ở bên ngoài"
    // Lỗi: Không thể phân tích dòng "509	Inside		Ở bên trong"
    { id: 510, word: "Confident", type: "adj.", meaning: "Tự tin" },
    { id: 511, word: "Confidently", type: "adv.", meaning: "Một cách tự tin" },
    { id: 512, word: "Confidence", type: "n.", meaning: "Sự tự tin" },
    { id: 513, word: "Happy", type: "adj.", meaning: "Vui vẻ, hạnh phúc" },
    { id: 514, word: "Unhappy", type: "adj.", meaning: "Bất hạnh, buồn rầu" },
    { id: 515, word: "Happiness", type: "n.", meaning: "Niềm hạnh phúc" },
    { id: 516, word: "Happily", type: "adv.", meaning: "Một cách hạnh phúc" },
    { id: 517, word: "Encouragement", type: "n.", meaning: "Sự khích lệ" },
    { id: 518, word: "Encouraging", type: "adj.", meaning: "Mang tính khích lệ" },
    { id: 519, word: "Encouraged", type: "adj.", meaning: "Cảm thấy được khích lệ" },
    { id: 520, word: "Please", type: "v.", meaning: "Làm hài lòng" },
    { id: 521, word: "Pleasure", type: "n.", meaning: "Sự hài lòng, niềm vui thích" },
    { id: 522, word: "Pleasant", type: "adj.", meaning: "Dễ chịu, thú vị" },
    { id: 523, word: "Unpleasant", type: "adj.", meaning: "Khó chịu" },
    { id: 524, word: "Pleased", type: "adj.", meaning: "Cảm thấy hài lòng" },
    { id: 525, word: "Development", type: "n.", meaning: "Sự phát triển" },
    { id: 526, word: "Developer", type: "n.", meaning: "Người phát triển" },
    { id: 527, word: "Developing", type: "adj.", meaning: "Đang phát triển" },
    { id: 528, word: "Developed", type: "adj.", meaning: "Đã phát triển" },
    { id: 529, word: "Invention", type: "n.", meaning: "Sự phát minh, vật phát minh" },
    { id: 530, word: "Inventor", type: "n.", meaning: "Nhà phát minh" },
    { id: 531, word: "Inventive", type: "adj.", meaning: "Có óc sáng tạo" },
    { id: 532, word: "Equip", type: "v.", meaning: "Trang bị" },
    { id: 533, word: "Well-equipped", type: "adj.", meaning: "Được trang bị tốt" },
    { id: 534, word: "Inform", type: "v.", meaning: "Thông báo, báo tin" },
    { id: 535, word: "Informative", type: "adj.", meaning: "Cung cấp nhiều thông tin" },
    { id: 536, word: "Uninformative", type: "adj.", meaning: "Thiếu thông tin" },
    { id: 537, word: "Communicate", type: "v.", meaning: "Giao tiếp" },
    { id: 538, word: "Communication", type: "n.", meaning: "Sự giao tiếp" },
    { id: 539, word: "Communicative", type: "adj.", meaning: "Cởi mở, thích giao tiếp" },
    { id: 540, word: "Communicator", type: "n.", meaning: "Người truyền tin" },
    { id: 541, word: "Collect", type: "v.", meaning: "Sưu tầm, thu gom" },
    { id: 542, word: "Collection", type: "n.", meaning: "Bộ sưu tập" },
    { id: 543, word: "Collector", type: "n.", meaning: "Người sưu tầm" },
    { id: 544, word: "Collective", type: "adj.", meaning: "Mang tính tập thể" },
    { id: 545, word: "Differ", type: "v.", meaning: "Khác biệt" },
    { id: 546, word: "Difference", type: "n.", meaning: "Sự khác biệt" },
    { id: 547, word: "Different", type: "adj.", meaning: "Khác nhau" },
    { id: 548, word: "Differently", type: "adv.", meaning: "Một cách khác nhau" },
    { id: 549, word: "Differentiate", type: "v.", meaning: "Phân biệt" },
    { id: 550, word: "Popularity", type: "n.", meaning: "Sự phổ biến" },
    { id: 551, word: "Popularize", type: "v.", meaning: "Làm cho phổ biến" },
    { id: 552, word: "Popularly", type: "adv.", meaning: "Một cách phổ biến" },
    { id: 553, word: "Interest", type: "n., v.", meaning: "Sự quan tâm / Làm quan tâm" },
    { id: 554, word: "Interesting", type: "adj.", meaning: "Thú vị (bản chất)" },
    { id: 555, word: "Interested", type: "adj.", meaning: "Cảm thấy quan tâm, thích thú" },
    { id: 556, word: "Memorable", type: "adj.", meaning: "Đáng nhớ" },
    { id: 557, word: "Memorably", type: "adv.", meaning: "Một cách đáng nhớ" },
    { id: 558, word: "Distract", type: "v.", meaning: "Làm xao nhãng" },
    { id: 559, word: "Distraction", type: "n.", meaning: "Sự xao nhãng" },
    { id: 560, word: "Distracting", type: "adj.", meaning: "Gây xao nhãng" },
    { id: 561, word: "Prevention", type: "n.", meaning: "Sự ngăn chặn" },
    { id: 562, word: "Preventive", type: "adj.", meaning: "Mang tính phòng ngừa" },
    { id: 563, word: "Preventable", type: "adj.", meaning: "Có thể ngăn chặn được" },
    { id: 564, word: "Nature", type: "n.", meaning: "Tự nhiên, bản chất" },
    { id: 565, word: "Naturally", type: "adv.", meaning: "Một cách tự nhiên" },
    { id: 566, word: "Environmental", type: "adj.", meaning: "Thuộc về môi trường" },
    { id: 567, word: "Environmentalist", type: "n.", meaning: "Nhà môi trường học" },
    { id: 568, word: "Economy", type: "n.", meaning: "Nền kinh tế" },
    { id: 569, word: "Economic", type: "adj.", meaning: "Thuộc về kinh tế" },
    { id: 570, word: "Economics", type: "n.", meaning: "Môn kinh tế học" },
    { id: 571, word: "Economical", type: "adj.", meaning: "Tiết kiệm" },
    { id: 572, word: "Economically", type: "adv.", meaning: "Về mặt kinh tế" },
    { id: 573, word: "Cool", type: "adj., v.", meaning: "Mát mẻ / Làm mát" },
    { id: 574, word: "Cooler", type: "n.", meaning: "Máy làm mát, thùng đá" },
    { id: 575, word: "Coolant", type: "n.", meaning: "Chất làm nguội" },
    { id: 576, word: "User", type: "n.", meaning: "Người dùng" },
    { id: 577, word: "Useless", type: "adj.", meaning: "Vô dụng" },
    { id: 578, word: "Usefully", type: "adv.", meaning: "Một cách hữu ích" },
    { id: 579, word: "Uselessly", type: "adv.", meaning: "Một cách vô dụng" },
    { id: 580, word: "Attractively", type: "adv.", meaning: "Một cách lôi cuốn" },
    { id: 581, word: "Destructive", type: "adj.", meaning: "Mang tính hủy diệt" },
    { id: 582, word: "Destructively", type: "adv.", meaning: "Một cách hủy diệt" },
    { id: 583, word: "Danger", type: "n.", meaning: "Sự nguy hiểm" },
    { id: 584, word: "Endanger", type: "v.", meaning: "Gây nguy hiểm" },
    { id: 585, word: "Dangerously", type: "adv.", meaning: "Một cách nguy hiểm" },
    { id: 586, word: "Success", type: "n.", meaning: "Sự thành công" },
    { id: 587, word: "Successfully", type: "adv.", meaning: "Một cách thành công" },
];

// Ghi chú: Nếu dùng trong HTML thông thường, chỉ cần nhúng <script src="vocab.js">
// Nếu dùng trong môi trường Module (ES6), bỏ comment dòng dưới:
// export default vocabList;